<?php
define('DB_HOST', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('DB_PORT', 3306);
define('DB_USER', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('DB_PASS', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('DB_NAME', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('API_APP_NAME', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('API_DEV_NAME', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('API_CERT_NAME', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('EbayAppRuName', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('AWS_API_KEY', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('AWS_API_SECRET_KEY', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('AWS_ASSOCIATE_TAG', 'SSSSSSSSSSSSSSSSSSSSSSS');
define('DB_PREFIX', '');
define('SITE_ADDRESS', 'http://megasellers.ru/');
?>
